[theme]
base = "light"
primaryColor = "#F8CD53"
backgroundColor = "#FBF9F1"
secondaryBackgroundColor = "#A3D9B8"
textColor = "#121212"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[server]
headless = false
port = 8501
